export const ADD_ITEM = 'ADD_ITEM'; 
export const REMOVE_ITEM = 'REMOVE_ITEM'; 
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'; 
export const CLEAR_CART = 'CLEAR_CART';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'; 
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'; 
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'; 
